version: '3.8'

services:

  database:
    image: mariadb:10.11
    container_name: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file:
      - .docker.env
    volumes:
      - mariadb:/var/lib/mysql

  php:
    build:
      context: ./docker/php
    container_name: php
    volumes:
      - ./:/var/www
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

volumes:
  mariadb: