version: '3.8'

services:

  database:
    image: mariadb:10.11
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: TestPass12345
      MYSQL_DATABASE: customer
      MYSQL_USER: app
      MYSQL_PASSWORD: TestPass12345
    volumes:
      - mariadb:/var/lib/mysql

  php:
    build:
      context: ./docker/php
    container_name: php
    volumes:
      - ./:/var/www
      - ./var:/var/www/var
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

volumes:
  mariadb: