version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:latest
    environment:
      MARIADB_DATABASE: customer
      MARIADB_USER: app
      MARIADB_ROOT_PASSWORD: TestPass12345
      MARIADB_PASSWORD: TestPass12345

    volumes:
      - database_data:/var/lib/mysql:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
