version: '3.8'

services:

  database:
    image: mariadb:10.11
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .docker.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql

  php:
    build:
      context: ./docker/php
    container_name: php
    volumes:
      - ./:/var/www
      - ./var:/var/www/var
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

volumes:
  mariadb: